#!/bin/sh
# Copyright (C) 2012  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: http://www.pitt-pladdy.com/blog/_20130324-161928_0000_Detailed_process_statistics_on_Cacti_via_SNMP_processes_/


IFS=' '
stats=`ps ax | sed 's/^.\{15\}\(.\).*$/\1/' | sort | uniq -c`
printf '%d\n' `echo $stats | grep D | sed 's/^ *\([0-9]*\) .*$/\1/'`
printf '%d\n' `echo $stats | grep R | sed 's/^ *\([0-9]*\) .*$/\1/'`
printf '%d\n' `echo $stats | grep S | sed 's/^ *\([0-9]*\) .*$/\1/'`
printf '%d\n' `echo $stats | grep T | sed 's/^ *\([0-9]*\) .*$/\1/'`
printf '%d\n' `echo $stats | grep Z | sed 's/^ *\([0-9]*\) .*$/\1/'`
